### ISSUE TITLE
DB: Address multi-container corruption issues

### ISSUE THREAD

**Issue by Athanasius** [EDCD/TickDetector#5]
I keep seeing at least one process fail to perform SQL operations because it thinks:

```
SqliteError: database disk image is malformed
```
It works on first run using the database dump that Phelbore gave us, but then at some point a stop/start cycle (even with my clean shutdown code additions) will start erroring.  Eventually only the EDDN process will run at all.

So, I propose that we migrate to using a mariadb instead.  I'm hoping that will be minimal javascript code changes, and there'll certainly be a Docker image we can use for an extra container to run that.  We'll just need to also configure a persistent storage volume for the data.

**Comment by Athanasius** [comment]
An alternative to this is changing how we present the sqlite file to the containers.

To avoid `SqliteError: database is locked ` issues (other than changing the code to retry, race conditions ahoy), the 'WAL' feature should be used.

But that utilise two extra files, `-wal` and `-shm` suffixes, which are not fully persistent.  Attempts to docker compose mount these, the same as the db file itself, just resulted in it creating directories of those names instead.

So, I'll experiment with putting the database file in a sub-directory and mounting *that* as a volume in the containers instead, that way all three will see the extra files for WAL as well.

**Comment by SayakMukhopadhyay** [comment]
If the files are not needed to be persistent, you can just create them inside the filepath of the container. In that way, those files will be removed every time the container is restarted.

Or do you _want_ the files to be persistent? Sorry, its not clear.

**Comment by Athanasius** [comment]
The problem currently is that **each container** creates the extra files and thus they're not actually co-operating and the state of the main DB file when they exit/are killed is inconsistent.

And, as noted, my attempts to:

1. Simply volume mount the extra files names as well - fails if they're not already created, as it creates directories instead.
2. Pre-create the files and volume mount them - also ends up with at least one ending up as a directory.  I can only assume this is because one of the containers removes them at some point very early, and then the startup of one of the other containers sees it doesn't exist and creates a directory for the volume mount instead.

Now, possibly this could be solved with some extra docker(-compose) configuration I'm not yet aware of... but isn't it simpler to just:

1. mkdir database && chmod 777 database # Because of the uid:gid mis-match
2. mv systems.sqlitedb database/
3. Adjust the code to use that sub-directory.
4. Adjust the docker-compose.yml to share the directory.

That way all three containers are simply using the same *directory* and **any** file they need to open/write/create/remove within it should be in sync across the containers.

**Comment by Athanasius** [comment]
And re: the persistency of the `-wal` and -`shm` files.  The issue is that for sqlite they're only **semi**-persistent.  They'll be created and used for a while as needed, and then removed, and then created again, and then ....
